### ISSUE TITLE
Unexpected mime type for zip files

### ISSUE THREAD

**Issue by MaximilianKresse** [Xantios/mimey#5]
copied from the original repository: https://github.com/ralouphie/mimey/issues/21

# Code
```php
(new \Mimey\MimeTypes())->getMimeType('zip');
```
# Expected result
```
'application/zip'
```
# Actual result
```
'application/x-gzip'
```

This wrong mime type means that e.g. Firefox and Chrome handle the file as gzip instead of a zip file and actively renaming the file.
The problem is probably the order in the default configuration:
https://github.com/Xantios/mimey/blob/develop/mime.types.php#L34

Is there a reason for this order or is this a bug?

**Comment by Xantios** [comment]
Hey,

Sorry for the late reply. for some reason Github did not send me a mail about this issue.

The mime type definitions are based on Apache HTTPd listing, they for the longest time have defined it in that way if I recall correctly there was some sort of conflict of definition on what a ZIP file should be.

To enforce compatibility for now you can look into [A Custom conversion](https://github.com/Xantios/mimey#custom-conversions)

But I am working on the updating mechanism for mime-types as we speak. so expect a update later today!

EDIT: Please notice that the gzip you are referring to is defined in the mime.types.custom!

**Comment by MaximilianKresse** [comment]
It looks like your last commit/release fixed the problem. Thanks!
